[package]
name = "apt-history"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
flate2 = "1.0.28"
regex = "1.10.2"
stybulate = "1.1.2"
